apiVersion: v1
kind: Pod
metadata:
  name: test-csi-persistent
spec:
  containers:
  - name: main
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: csi-pvc
