apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-pv
  labels:
    type: local
spec:
  storageClassName: csi-bottle-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: bottle.csi.act3-ace.io
    claimRef: sdsdfadsf
    volumeHandle: foo
    volumeAttributes:
      # Specify your bottle here.
      bottle: ghcr.io/nathan-joslin/bottles/mnist:v1.7
      selector: "subset=train,component=image|usage=true"
