apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
  annotations:
    bottle.csi.act3-ace.io/bottle: ghcr.io/nathan-joslin/bottles/mnist:v1.7
    bottle.csi.act3-ace.io/selector: "subset=train,component=image|usage=true"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-bottle-sc
