apiVersion: v1
kind: Pod
metadata:
  name: test-csi
spec:
  containers:
  - name: main
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  volumes:
  - name: data
    csi:
      driver: bottle.csi.act3-ace.io
      volumeAttributes:
        # Specify your bottle here.
        bottle: ghcr.io/nathan-joslin/bottles/mnist:v1.7
        # bottle: bottle:sha256:8d90d933cffe2c82c383e1a2ecd6da700fc714a9634144dd7a822a1d77432566
        # Specify selectors to limit data
        # selector: "subset=train"
        #selector: "subset=train,component=image"
        selector: "subset=train,component=image|type=usage"
