{{- if .Values.prometheus.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "csi-bottle.fullname" . }}
  labels:
    {{- include "csi-bottle.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      {{- include "csi-bottle.selectorLabels" . | nindent 6 }}
{{- end }}
