apiVersion: v1
kind: Service
metadata:
  name: {{ include "csi-bottle.fullname" . }}
  labels:
    {{- include "csi-bottle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9102
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "csi-bottle.selectorLabels" . | nindent 4 }}
